export type Seller = 'Private' | 'Dealer lot';

export type Car = {
  id: string;
  year: number;
  make: string;
  model: string;
  trim: string;
  price: number;
  priceNote: string;
  miles: number;
  city: string;
  drive: string;
  owners: string;
  title: string;
  seller: Seller;
  color: string;
  drivetrain: string;
  mpg: string;
  verdict: string;
  photos: string[];
  listingUrl: string;
  sellerSays: string;
  why: string;
  watch: string[];
  check: string[];
};

export const CHECKED_ON = 'September 30, 2026';

export const MARKET_NOTES = [
  'The $5,000 to $8,000 band around College Station is mostly 2007 to 2014 cars with 70,000 to 170,000 miles. A 2018 or newer car at this price usually means the miles are missing, the title is messy, or tax and title push it past the budget.',
  'The models that keep showing up as the ones that still run are Toyota Corolla, Toyota Camry from 2010 on (the 2.5L), Honda Civic, Honda Accord with the 2.4 four-cylinder, Honda Fit, and Honda CR-V. A Mazda3 is fine too. This deck is only cars from that group.',
  'Skip these in this budget even when the price looks friendly: Nissan Altima, Rogue, and Maxima (their CVT transmissions fail), Ford Focus and Fiesta automatics (the dual-clutch transmission), Ford Escape with the small turbo (coolant can leak into the engine), Jeep Patriot, and Dodge Journey. Those were the cars actually posted in College Station today.',
  'No used car is guaranteed. A pre-purchase inspection is the guarantee, about $150 to $200 at an independent shop, before you pay. "Clean title" in an ad is the seller talking. Ask for the VIN and read a history report yourself. Houston-area cars also need a flood sniff: wet carpets, a water line in the spare well, a musty trunk.',
];

export const CARS: Car[] = [
  {
    id: 'accord-2012-houston',
    year: 2012,
    make: 'Honda',
    model: 'Accord',
    trim: 'SE',
    price: 7500,
    priceNote: 'or best offer',
    miles: 68600,
    city: 'Houston',
    drive: 'about 1 hr 40 min',
    owners: 'Not stated',
    title: 'Clean title, seller says it is in hand',
    seller: 'Private',
    color: 'Black, leather',
    drivetrain: '2.4L four-cylinder, 5-speed automatic, front-wheel drive',
    mpg: 'about 25 to 28 combined',
    verdict: 'Best bet',
    photos: [
      'https://images.craigslist.org/00m0m_SqNN7mdiIH_0x20oM_600x450.jpg',
      'https://images.craigslist.org/00s0s_9cJG2j1gBuh_0x20oM_600x450.jpg',
    ],
    listingUrl: 'https://www.craigslist.org/view/d/houston-2012-honda-accord-se-69k-miles/i6vdoN2SeSNTW77buuhQYg',
    sellerSays:
      'Private seller. 68,600 miles, clean title in hand, two keys, alloy wheels. Hail dents, scratches, and paint wear. Tires are older. Washer nozzles need cleaning or replacement. They are done with the car and will take a reasonable offer.',
    why: 'Lowest miles in the whole search, on the simple 2.4 four-cylinder with a regular automatic. Not a CVT, not the V6. The seller already listed the ugly parts, and they are cosmetic. This is the one to go see first.',
    watch: [
      '2008 to 2012 Accords can tick for a second on a cold start. That is usually the VTC actuator. Annoying, and usually not the end of the engine.',
      'Some of these engines use oil. Check the dipstick before you fall in love with the mileage.',
      'Hail and old tires cost money. They do not cost "new engine" money. Budget a set of tires if the tread is done.',
    ],
    check: [
      'Cold start with the hood open. A rattle that vanishes once it is warm is the known tick.',
      'Dipstick, then look under the car for a fresh drip.',
      'Title in the seller\'s name, then a history report from the VIN before you drive down. Houston cars get a flood sniff too.',
    ],
  },
  {
    id: 'crv-2007-seabrook',
    year: 2007,
    make: 'Honda',
    model: 'CR-V',
    trim: 'LX',
    price: 7200,
    priceNote: '',
    miles: 134600,
    city: 'Seabrook',
    drive: 'about 2 hr',
    owners: 'Original owner',
    title: 'Clean title, no accident claimed',
    seller: 'Private',
    color: 'Black on black',
    drivetrain: '2.4L four-cylinder, automatic. Two-wheel or all-wheel drive was not stated.',
    mpg: 'about 20 to 23 combined',
    verdict: 'First owner',
    photos: [
      'https://images.craigslist.org/00V0V_bYD9GyPIc7W_0CI0t2_600x450.jpg',
      'https://images.craigslist.org/00O0O_1RqbnP4Dfn6_0CI0t2_600x450.jpg',
      'https://images.craigslist.org/00A0A_j5Xt5mXBIZD_0CI0t2_600x450.jpg',
    ],
    listingUrl: 'https://www.craigslist.org/view/d/seabrook-2007-honda-crv-lx-for-sale/phjZDY5VigurrQDUpfX6Uo',
    sellerSays:
      'Original owner. Garage kept, no accident, clean title, owner\'s manual with a maintenance record, and three keys. Black, 134,600 miles, $7,200.',
    why: 'This is the first-owner car in the pile. Same tough Honda 2.4 family as the Accord, with the paperwork story you asked for: one person, records, keys, a garage.',
    watch: [
      'The air conditioner compressor on 2007 to 2011 CR-Vs fails often, and the repair is commonly over $1,000. The ad never says the A/C was replaced.',
      '134,000 miles is fine for this generation if the A/C and the transmission are honest.',
    ],
    check: [
      'A/C on max for ten minutes, in the sun if you can.',
      'The title should show one long ownership, not a fresh flip.',
      'Spare-tire well and carpets for water. Seabrook is on the bay side of Houston.',
    ],
  },
  {
    id: 'camry-2010-spring',
    year: 2010,
    make: 'Toyota',
    model: 'Camry',
    trim: 'LE',
    price: 7450,
    priceNote: '',
    miles: 117000,
    city: 'Spring',
    drive: 'about 1 hr 50 min',
    owners: 'Two owners since new',
    title: 'Clean Texas title',
    seller: 'Private',
    color: 'Silver, gray cloth',
    drivetrain: '2.5L four-cylinder (169 hp), automatic, front-wheel drive',
    mpg: 'about 25 to 28 combined',
    verdict: 'Strong',
    photos: [
      'https://images.craigslist.org/00h0h_bWn45wrwURM_0C60t2_600x450.jpg',
      'https://images.craigslist.org/00v0v_jzVdMN40MJK_0CI0t2_600x450.jpg',
      'https://images.craigslist.org/00Y0Y_4n8m1dPkcNz_0BJ0t2_600x450.jpg',
      'https://images.craigslist.org/00a0a_ij8fhCAZwoU_0CI0t2_600x450.jpg',
      'https://images.craigslist.org/00c0c_X1pMi2O8G6_0Ct0t2_600x450.jpg',
      'https://images.craigslist.org/00U0U_dmtzxwS0bvj_0CI0t2_600x450.jpg',
    ],
    listingUrl: 'https://www.craigslist.org/view/d/spring-toyota-camry-le-low-miles-owner/uL5gvdY5QMk4yjrvWvCkrs',
    sellerSays:
      'Two owners since new, 117,000 miles, 39 service records on Carfax, newer tires, cold A/C, non-smoker, clean Texas title. Power windows, locks, seat, cruise, remote entry.',
    why: 'This is the Camry generation you want. The 2010 2.5L replaced the 2007 to 2009 2.4 that burns oil. Two owners and a long service list beat a mysterious low-mile ad.',
    watch: [
      '117,000 is normal, not low. You are buying a maintained car, not a garage queen.',
      'Water pump and suspension are the usual age items. They are not a pattern of these engines dying.',
    ],
    check: [
      'See the Carfax. Do not take "39 records" as a sentence.',
      'Cold A/C on a warm afternoon, and a highway pull with no shudder.',
      'Houston-north flood sniff, then the VIN report.',
    ],
  },
  {
    id: 'civic-2014-dallas',
    year: 2014,
    make: 'Honda',
    model: 'Civic',
    trim: 'LX',
    price: 7000,
    priceNote: 'cash',
    miles: 167090,
    city: 'Dallas',
    drive: 'about 2 hr 50 min',
    owners: 'One owner, personal use',
    title: 'Clean title',
    seller: 'Private',
    color: 'Silver, gray interior',
    drivetrain: '1.8L four-cylinder, 5-speed automatic, front-wheel drive',
    mpg: 'about 28 to 32 combined',
    verdict: 'First owner',
    photos: [
      'https://images.craigslist.org/00O0O_7Jcz04Ho69z_0qh0t2_600x450.jpg',
      'https://images.craigslist.org/00N0N_2xtxCP3AOn1_0CI0hV_600x450.jpg',
      'https://images.craigslist.org/00x0x_8PLXw4ebhS2_0A80t2_600x450.jpg',
      'https://images.craigslist.org/00X0X_j0uwMtGgi5g_0CI0fX_600x450.jpg',
      'https://images.craigslist.org/00e0e_hYFPNAho56q_0lM0t2_600x450.jpg',
      'https://images.craigslist.org/00l0l_jGB7Ka12mqX_0CI0j4_600x450.jpg',
    ],
    listingUrl: 'https://www.craigslist.org/view/d/dallas-2014-honda-civic-lx-7000/x73Yy1HGbxJ8vSehEAXWaD',
    sellerSays:
      'One owner, personal use, clean title, serviced at Honda. Silver LX, 167,090 miles. Slight damage on the driver-side front bumper. Cash.',
    why: 'The first-owner Civic, and the LX kept a normal automatic instead of the CVT that the fancier 2014 Civics used. Honda service history is the right kind of boring.',
    watch: [
      '167,000 miles is the top of what still belongs in a $7,000 conversation. The ownership is the reason to look. The odometer is the reason to be picky.',
      'Bumper damage is minor only if the structure behind it is straight.',
    ],
    check: [
      'Ask for the Honda service history, not just the claim.',
      'Look behind the bumper and drive it for a pull to one side.',
      'This is a long day from College Station. Get the title photo before you go.',
    ],
  },
  {
    id: 'civic-2008-spring',
    year: 2008,
    make: 'Honda',
    model: 'Civic',
    trim: 'EX coupe',
    price: 8000,
    priceNote: '',
    miles: 108819,
    city: 'Spring',
    drive: 'about 1 hr 50 min',
    owners: 'Not stated',
    title: 'Clean Texas title, in hand',
    seller: 'Private',
    color: 'Not stated',
    drivetrain: '1.8L four-cylinder, automatic, front-wheel drive',
    mpg: 'about 28 to 32 combined',
    verdict: 'Strong',
    photos: [
      'https://images.craigslist.org/00l0l_2mk9rO6fHLY_0h60hO_600x450.jpg',
      'https://images.craigslist.org/00M0M_9ZHsxE9ftLj_0kW0eM_600x450.jpg',
      'https://images.craigslist.org/00K0K_66x8L5Ko71T_0pO0jm_600x450.jpg',
      'https://images.craigslist.org/00L0L_fKHQkVObPAT_0pO0dG_600x450.jpg',
      'https://images.craigslist.org/00d0d_aTb8o700C5l_0pO0jm_600x450.jpg',
      'https://images.craigslist.org/00909_jcTcD8IvOOE_0ms0fw_600x450.jpg',
    ],
    listingUrl: 'https://www.craigslist.org/view/d/spring-2008-honda-civic-ex-coupe-108k/dP6wn6ukdH2hdiryY5UtWw',
    sellerSays:
      'EX coupe, 108,819 miles, automatic, clean Texas title. Recent work they list: engine mounts, shocks, brakes, and fresh fluids. 18-inch wheels and run-flat tires.',
    why: 'They already did the jobs this Civic generation is known for, especially the engine mounts. That is the opposite of a car that was patched for the ad. It sits at the ceiling of the budget, and a coupe has a tighter back seat.',
    watch: [
      '2006 to 2011 Civic paint can peel on the roof and trunk. Look in sunlight.',
      'Run-flats ride firmly and cost more to replace than normal tires.',
    ],
    check: [
      'Shift into drive with the brake on. A bad mount makes the engine rock. They claim the mounts are new, so it should sit still.',
      'Title in their name, and a flood sniff. Spring is north Houston.',
    ],
  },
  {
    id: 'rav4-2012-flower-mound',
    year: 2012,
    make: 'Toyota',
    model: 'RAV4',
    trim: 'V6',
    price: 6800,
    priceNote: '',
    miles: 155000,
    city: 'Flower Mound',
    drive: 'about 3 hr',
    owners: 'One owner',
    title: 'Not stated in the ad',
    seller: 'Private',
    color: 'Not stated',
    drivetrain: '3.5L V6, automatic, front-wheel drive',
    mpg: 'about 19 to 21 combined',
    verdict: 'First owner',
    photos: [
      'https://images.craigslist.org/00l0l_gIlk4ic0C5E_0lM0t2_600x450.jpg',
      'https://images.craigslist.org/00P0P_5rI7ZMd1cn5_0lM0t2_600x450.jpg',
      'https://images.craigslist.org/00Q0Q_i6JEKcJCMBZ_0CI0t2_600x450.jpg',
      'https://images.craigslist.org/00K0K_9uUrtnlxUZU_0CI0t2_600x450.jpg',
      'https://images.craigslist.org/00D0D_EOK7288UeQ_0t20CI_600x450.jpg',
      'https://images.craigslist.org/00j0j_cfXbfAQidxL_0t20CI_600x450.jpg',
    ],
    listingUrl: 'https://www.craigslist.org/view/d/flower-mound-2012-toyota-rav4-v6-155k/7j8XgfM2G6GVs7h9EeendF',
    sellerSays:
      'One owner, about 155,000 miles, V6, front-wheel drive, no check-engine light, no warning lights, no leaks. New battery, Continental tires, sunroof, backup camera, cloth.',
    why: 'One owner, and this V6 is a strong Toyota engine. You pay for it at the pump. Pick this if you want the space. Skip it if you only need a commuter.',
    watch: [
      'It uses more gas than every sedan here. That is the whole trade.',
      'The ad never says "clean title." One owner is a claim until the title history says so.',
      '155,000 miles of normal wear is still 155,000 miles.',
    ],
    check: [
      'VIN and a history report before the three-hour drive.',
      'Cold start, A/C, and the sunroof seal.',
    ],
  },
  {
    id: 'camry-2007-austin',
    year: 2007,
    make: 'Toyota',
    model: 'Camry',
    trim: 'LE',
    price: 7200,
    priceNote: '',
    miles: 79000,
    city: 'Austin',
    drive: 'about 1 hr 40 min',
    owners: 'Two owners',
    title: 'Clean title, in hand',
    seller: 'Private',
    color: 'Not stated',
    drivetrain: '2.4L four-cylinder, automatic, front-wheel drive',
    mpg: 'about 24 to 27 combined',
    verdict: 'Check first',
    photos: [
      'https://images.craigslist.org/00n0n_4vCdTZSlID1_12w0Mo_600x450.jpg',
      'https://images.craigslist.org/01010_2SQs7Oynjr1_12w0Mo_600x450.jpg',
      'https://images.craigslist.org/00404_dKvoz4GTNwi_12w0Mo_600x450.jpg',
      'https://images.craigslist.org/00T0T_kV1Z5AiquFn_12w0Mo_600x450.jpg',
      'https://images.craigslist.org/00T0T_3E26oA4tOH7_12w0Mo_600x450.jpg',
      'https://images.craigslist.org/00m0m_e2C6ZgFq7Wj_12w0Mo_600x450.jpg',
    ],
    listingUrl: 'https://www.craigslist.org/view/d/austin-2007-toyota-camry-le-79k-miles/aN4sosDcdtg7asng2DFprW',
    sellerSays:
      '79,000 miles, two owners, clean title, current state inspection, non-smoker, cold A/C. At 63,000 miles they replaced tires, lower control arms, sway bar links, wheel bearings, struts, brakes, and rotors. Inspections welcome.',
    why: 'Real miles this low are rare at $7,200, and the suspension work is already done. It is here because of the miles, not because this is the safe Camry year.',
    watch: [
      'The 2007 to 2009 2.4L Camry is the one that burns oil. Toyota\'s old warranty extension is expired. If it uses a quart every thousand miles, you live by the dipstick.',
      'That is why the 2010 Camry ranks higher even with more miles.',
    ],
    check: [
      'Dipstick before the drive and after. Ask how often they add oil. Hesitation is a no.',
      'Blue smoke on startup.',
      'They invited an inspection. Use that. Do not skip it because the miles look pretty.',
    ],
  },
  {
    id: 'accord-2011-pflugerville',
    year: 2011,
    make: 'Honda',
    model: 'Accord',
    trim: 'LX-P',
    price: 5990,
    priceNote: '',
    miles: 114000,
    city: 'Pflugerville',
    drive: 'about 1 hr 45 min',
    owners: 'Second owner',
    title: 'Clean title',
    seller: 'Private',
    color: 'Not stated',
    drivetrain: 'Four-cylinder, automatic, front-wheel drive',
    mpg: 'about 25 to 28 combined',
    verdict: 'Strong',
    photos: [
      'https://images.craigslist.org/00T0T_lbSQGD93hZS_0CI0t2_600x450.jpg',
      'https://images.craigslist.org/01212_8t9UTkegY1o_0CI0t2_600x450.jpg',
      'https://images.craigslist.org/00z0z_aWo81Acx9zk_0CI0t2_600x450.jpg',
      'https://images.craigslist.org/00202_3TqnTF7vjU1_0CI0t2_600x450.jpg',
      'https://images.craigslist.org/00W0W_k4Xu5WOT57C_0CI0t2_600x450.jpg',
      'https://images.craigslist.org/00x0x_jXEj2GtV97r_0CI0t2_600x450.jpg',
    ],
    listingUrl: 'https://www.craigslist.org/view/d/pflugerville-2011-honda-accord-lx/e6wWzwbnC7qMxRsTo6kKF9',
    sellerSays:
      'Second owner, 114,000 miles, clean title, four-cylinder automatic, cold A/C. They say the engine and transmission work and it is a daily driver. The ad is short.',
    why: 'Same good Accord idea as the Houston car, about $1,500 less, with a second owner. You know less, because they wrote less.',
    watch: [
      '2008 to 2011 four-cylinder Accords can use oil and can tick on a cold start.',
      'A short ad hides condition. The price is only good if the car matches the photos.',
    ],
    check: [
      'Cold start, dipstick, and a title that matches the person you meet.',
      'Because the writeup is thin, the inspection matters more here than on the Houston Accord.',
    ],
  },
  {
    id: 'fit-2013-grand-prairie',
    year: 2013,
    make: 'Honda',
    model: 'Fit',
    trim: 'Sport',
    price: 7995,
    priceNote: 'plus tax, title, and license',
    miles: 106000,
    city: 'Grand Prairie',
    drive: 'about 3 hr',
    owners: 'Two owners',
    title: 'Clean title',
    seller: 'Dealer lot',
    color: 'Blue, black interior',
    drivetrain: '1.5L four-cylinder, automatic with paddle shifters, front-wheel drive',
    mpg: 'about 33 to 38 combined',
    verdict: 'Check first',
    photos: [
      'https://images.craigslist.org/01212_jdxThwrTLX7_0CI0t2_600x450.jpg',
      'https://images.craigslist.org/00202_fsIUyZag7WA_0CI0t2_600x450.jpg',
      'https://images.craigslist.org/01616_btkyQ59IekX_0CI0t2_600x450.jpg',
      'https://images.craigslist.org/00G0G_48hjqJripBu_0CI0t2_600x450.jpg',
      'https://images.craigslist.org/00Y0Y_9g06HEK0izq_0CI0t2_600x450.jpg',
      'https://images.craigslist.org/00B0B_l1Hz9VOHmob_0CI0t2_600x450.jpg',
    ],
    listingUrl: 'https://www.craigslist.org/view/d/grand-prairie-2013-honda-fit-sport-auto/dAM6vT33EZup24XPUX7vtt',
    sellerSays:
      'Dealer-style ad. $7,995 plus tax, title, and license. Clean title, two owners, 106,000 miles, blue, non-smoker, cold A/C, cruise, keyless entry.',
    why: 'The Fit is the small car that does not fall apart, and 106,000 miles with two owners is a fair example. The catch is the out-the-door price, and you are buying from a lot, not from the driver.',
    watch: [
      'Plus tax, title, and license can push this past $8,500. That leaves the budget.',
      'Spark plugs and ignition coils are due around this mileage on a Fit.',
    ],
    check: [
      'Get the out-the-door number in writing before a three-hour drive.',
      'Fold the seats, run the A/C, and do not add their fees on top of an $8,000 cap without noticing.',
    ],
  },
  {
    id: 'camry-2014-dallas',
    year: 2014,
    make: 'Toyota',
    model: 'Camry',
    trim: 'LE',
    price: 5999,
    priceNote: 'cash',
    miles: 148000,
    city: 'Dallas',
    drive: 'about 2 hr 50 min',
    owners: 'Not stated',
    title: 'Not stated in the ad',
    seller: 'Private',
    color: 'Not stated',
    drivetrain: '2.5L four-cylinder, 6-speed automatic, front-wheel drive',
    mpg: 'about 25 to 28 combined',
    verdict: 'Check first',
    photos: [
      'https://images.craigslist.org/00808_48P2HXH0GwM_13O0Nm_600x450.jpg',
      'https://images.craigslist.org/00g0g_dSvXUmfV60w_13O0Nm_600x450.jpg',
      'https://images.craigslist.org/00303_knjfc5CopI6_13O0Nm_600x450.jpg',
      'https://images.craigslist.org/00M0M_7yEikLoufBn_13O0Nm_600x450.jpg',
      'https://images.craigslist.org/00M0M_1sEscwA5uFj_13O0Nm_600x450.jpg',
      'https://images.craigslist.org/00404_7rAwLyTvOEh_13O0Nm_600x450.jpg',
    ],
    listingUrl: 'https://www.craigslist.org/view/d/dallas-2014-toyota-camry-148k-miles/sUkjPdurF9rcgNY6r263Xn',
    sellerSays:
      '148,000 miles, cold A/C, four new Goodyear tires, cash, $5,999. They call it clean and say it runs well. No owner count and no title sentence.',
    why: 'A 2012 to 2017 Camry is the boring correct daily driver. New tires and cold A/C at $5,999 is priced like an honest 148,000-mile car, not a fantasy and not a wreck.',
    watch: [
      'They never said clean title or how many owners. That is the whole risk.',
      'At this mileage you are buying service history. The 6-speed likes its fluid changed.',
    ],
    check: [
      'Photo of the title, in their name, before you leave.',
      'Receipts, especially transmission fluid.',
    ],
  },
  {
    id: 'civic-2014-frisco',
    year: 2014,
    make: 'Honda',
    model: 'Civic',
    trim: 'EX-L',
    price: 7500,
    priceNote: '',
    miles: 143000,
    city: 'Frisco',
    drive: 'about 3 hr 15 min',
    owners: 'Not stated',
    title: 'Clean title',
    seller: 'Private',
    color: 'White, black leather',
    drivetrain: '1.8L four-cylinder, CVT, front-wheel drive',
    mpg: 'about 30 combined',
    verdict: 'Check first',
    photos: [
      'https://images.craigslist.org/00S0S_looAC1gYZZI_0CI0t2_600x450.jpg',
      'https://images.craigslist.org/00101_4GqWDdf32RV_0CI0t2_600x450.jpg',
      'https://images.craigslist.org/00A0A_eCN7vtcEZJf_0CI0t2_600x450.jpg',
      'https://images.craigslist.org/00505_3cSKgpBF1T0_0CI0t2_600x450.jpg',
      'https://images.craigslist.org/00x0x_gmKhJhixRp0_0CI0t2_600x450.jpg',
      'https://images.craigslist.org/00202_lfqtpQ83Ufd_0CI0t2_600x450.jpg',
    ],
    listingUrl: 'https://www.craigslist.org/view/d/frisco-2014-honda-civic-4dr-exl-143k/85qqFHedv9c9YVSVn6Xyb9',
    sellerSays:
      'Clean title, 143,000 miles, white, black leather, heated seats, sunroof, push-button start, garaged. They say the oil, filters, and transmission fluid were just done. No major dents.',
    why: 'A loaded Civic at a fair mile-for-dollar number, and the fluids were just touched. It is lower in the deck because this trim uses a CVT, and Frisco is a long drive.',
    watch: [
      '2014 EX-L Civics use Honda\'s CVT. It is calmer than a Nissan CVT, and a shudder pulling away is still a reason to leave.',
      'A transmission flush only counts if there is a receipt.',
    ],
    check: [
      'Slow roll from a stop, then a highway merge. Feel for shudder.',
      'Sunroof: stained headliner means a clogged drain.',
    ],
  },
  {
    id: 'fit-2009-fort-worth',
    year: 2009,
    make: 'Honda',
    model: 'Fit',
    trim: 'Sport',
    price: 5500,
    priceNote: 'negotiable',
    miles: 123000,
    city: 'Fort Worth',
    drive: 'about 3 hr',
    owners: 'Not stated',
    title: 'Not stated in the ad',
    seller: 'Private',
    color: 'Not stated',
    drivetrain: '1.5L four-cylinder, automatic, front-wheel drive',
    mpg: 'about 28 city, 35 highway, per the seller',
    verdict: 'Check first',
    photos: [
      'https://images.craigslist.org/00c0c_90UKePFdxtQ_0t20CI_600x450.jpg',
      'https://images.craigslist.org/00F0F_aizYPZbgQWm_0t20CI_600x450.jpg',
      'https://images.craigslist.org/00909_1LMFazRHN4H_0t20CI_600x450.jpg',
      'https://images.craigslist.org/00q0q_iSyGFHEq0U4_0t20CI_600x450.jpg',
      'https://images.craigslist.org/01111_890QY0SdWld_0t20CI_600x450.jpg',
      'https://images.craigslist.org/00m0m_kF2YqzWfGnA_0t20CI_600x450.jpg',
    ],
    listingUrl: 'https://www.craigslist.org/view/d/fort-worth-2009-honda-fit-sport/h7jgT1w26cThTSU84STWGW',
    sellerSays:
      '123,000 miles, no check-engine light, heat and A/C work, fog lights. It needs a pair of front tires. $5,500, negotiable.',
    why: 'Right car, and they told you about the tires instead of hiding them. A pair of tires is a few hundred dollars, not a rebuild. It is last because the title and the owner count are missing, and Fort Worth is far.',
    watch: [
      'Silence on the title is the risk, not the tire tread.',
      '$5,500 is the floor of this budget. Cheap is fine only after the title photo exists.',
    ],
    check: [
      'Title photo before you leave College Station.',
      'Price the front tires, and look at the rear tread so you are not buying four.',
    ],
  },
];
