export type Seller = 'Dealer';

export type Car = {
  id: string;
  year: number;
  make: string;
  model: string;
  trim: string;
  price: number;
  priceNote: string;
  miles: number;
  city: string;
  drive: string;
  owners: string;
  title: string;
  seller: Seller;
  dealer: string;
  color: string;
  drivetrain: string;
  mpg: string;
  verdict: string;
  photos: string[];
  listingUrl: string;
  vin: string;
  sellerSays: string;
  why: string;
  watch: string[];
  check: string[];
};

export type YearGrade = 'better' | 'typical' | 'worse';

export type YearRecord = {
  grade: YearGrade;
  note: string;
};

/** Complaint-year check, same idea as carbuyer-ontario. Not a Texas price. */
export const YEAR_RECORDS: Record<string, YearRecord> = {
  "corolla-2010-spring": {
    grade: "better",
    note: "Fewer complaints than some nearby Corolla years. The common theme on this era is airbags, the industry recall, not the 1.8 engine.",
  },
  "civic-2012-sugar-land": {
    grade: "typical",
    note: "Normal complaint volume for a Civic. The common theme on some 2014s is the powertrain. This 2012 LX still uses a regular 5-speed automatic.",
  },
  "fit-2013-houston": {
    grade: "typical",
    note: "Normal complaint volume for a Fit. The common theme is airbags.",
  },
  "camry-2010-spring": {
    grade: "typical",
    note: "Normal complaint volume. The common theme is speed control. This is the 2.5L Camry, not the oil-burning 2.4.",
  },
  "civic-2011-austin": {
    grade: "typical",
    note: "Normal Civic complaint volume. This LX uses a regular automatic.",
  },
  "rav4-2012-rosenberg": {
    grade: "typical",
    note: "Normal complaint volume for a RAV4 of this era. The common theme is wipers, not the engine.",
  },
  "civic-2009-houston": {
    grade: "typical",
    note: "Normal complaint volume. The common theme on this Civic era is airbags.",
  },
  "accord-2008-houston": {
    grade: "better",
    note: "Fewer owner complaints than the Accord years around 2008 to 2012. The common theme is seats, not the engine.",
  },
  "corolla-2013-houston": {
    grade: "better",
    note: "Fewer complaints than nearby Corolla years. The common theme is airbags.",
  },
  "rav4-2012-sugar-land": {
    grade: "typical",
    note: "Normal RAV4 complaint volume. Wipers are the common theme, not the 2.5 engine.",
  },
  "crv-2011-houston": {
    grade: "typical",
    note: "Normal CR-V complaint volume. The common theme is airbags, not the 2.4.",
  },
  "corolla-2009-killeen": {
    grade: "typical",
    note: "Normal Corolla complaint volume for this era.",
  },
  "accord-2012-spring": {
    grade: "better",
    note: "Fewer complaints than nearby Accord years. Seats are the common theme, not the 2.4.",
  },
  "crv-2013-jersey-village": {
    grade: "typical",
    note: "Normal CR-V volume. This 2013 is the newer body, still a 2.4 with a regular automatic.",
  },
  "camry-2016-san-antonio": {
    grade: "better",
    note: "The 2012 to 2017 Camry 2.5L has a much cleaner complaint record than the 2007 to 2009 2.4.",
  },
  "fit-2015-buda": {
    grade: "typical",
    note: "Normal Fit complaint volume. This 2015 LX is the year Honda put a CVT in the Fit.",
  },
  "accord-2015-sugar-land": {
    grade: "typical",
    note: "2013 to 2017 Accords moved to a CVT. Complaint volume on the four-cylinder is ordinary. The transmission is the new question.",
  },
  "camry-2008-nederland": {
    grade: "worse",
    note: "The 2007 to 2009 Camry 2.4 draws about three times the complaints of nearby years. Brakes are the headline. Oil use is the other bill.",
  },
  "camry-2009-jersey-village": {
    grade: "worse",
    note: "Same 2007 to 2009 2.4 Camry complaint spike. This XLE is the nicer trim of the risky engine.",
  },
  "crv-2007-dallas": {
    grade: "typical",
    note: "Normal CR-V complaint volume. Airbags are the common theme, not the engine.",
  },
  "fit-2011-lavon": {
    grade: "typical",
    note: "Normal Fit complaint volume. This 2011 Sport is still the regular automatic.",
  },
  "rav4-2008-brookshire": {
    grade: "typical",
    note: "The 2008 RAV4 2.4 is older than the 2012 2.5. Complaint volume is ordinary. Oil use is less famous here than on the Camry, and it is still worth a dipstick check.",
  },
};

export const CHECKED_ON = 'September 30, 2026';

export const MARKET_NOTES = [
  "These are dealer listings on CarGurus within about 180 miles of College Station, asking $5,000 to $8,000, checked September 30, 2026. Honda and Toyota only: Corolla, Camry, Civic, Accord, Fit, CR-V, and RAV4.",
  "CarMax does not really stock this budget. The Civics and Corollas on dealer lots near here mostly start around $11,000. CarGurus is where the $5,000 to $8,000 dealer cars actually are, and they are older, usually 2008 to 2016, with 100,000 to 175,000 miles.",
  "A great price on CarGurus means the ask is under their estimate for similar cars. It does not mean the car is fresh, and it does not include dealer fees. Ask for the out-the-door number.",
  "The 2007 to 2009 Camry 2.4 is on the list only with a warning. It burns oil. The 2010 and newer Camry 2.5 is the one to prefer. Four-cylinder Accords from 2008 to 2012 are here. V6 Accords are not, because the timing belt is a separate bill. 2014 and newer Accord and Fit automatics on this list use a CVT. Listen for shudder.",
  "The Board still uses the complaint-year check from carbuyer-ontario, a Hack the North project. Their prices are Ontario ads in Canadian dollars, so they are not used as a Texas bargain score.",
  "No used car is guaranteed. A pre-purchase inspection is the guarantee, about $150 to $200, before you pay. Read the history report on the VIN yourself.",
];

export const CARS: Car[] = [
  {
    id: "corolla-2010-spring",
    year: 2010,
    make: "Toyota",
    model: "Corolla",
    trim: "LE",
    price: 5995,
    priceNote: "CarGurus estimate $7,883",
    miles: 115289,
    city: "Spring, TX",
    drive: "65 mi",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "J & M Imports",
    color: "Blue",
    drivetrain: "132 hp 1.8L I4, Transmission was not named on the listing",
    mpg: "Listed on CarGurus with the car",
    verdict: "Best bet",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/18/11/26/2010_toyota_corolla-pic-7829841297525655938-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/459289290",
    vin: "JTDBU4EE2AJ060575",
    sellerSays: "J & M Imports in Spring, TX. 2010 Toyota Corolla LE. Blue. 132 hp 1.8L I4. Transmission was not named on the listing. 115,289 miles. 12 days on CarGurus. Asking $5,995.",
    why: "CarGurus rates this a great price. Their estimate is $7,883, about $1,888 under that number. This is the right cheap car: a 1.8 Corolla, a great-price rating, and only 65 miles from College Station.",
    watch: [
      "The 1.8 four-cylinder and a regular automatic are the combination you want. There is no CVT here.",
      "The listing left the transmission name blank. Confirm it is an automatic and that it shifts cleanly.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you drive over.",
      "Ask for the out-the-door price. Doc fees can push a car in this list past $8,000.",
      "Pay for a pre-purchase inspection. A dealer lot is not the same thing as a clean mechanical bill.",
    ],
  },
  {
    id: "civic-2012-sugar-land",
    year: 2012,
    make: "Honda",
    model: "Civic",
    trim: "LX",
    price: 7000,
    priceNote: "CarGurus estimate $8,775",
    miles: 133500,
    city: "Sugar Land, TX",
    drive: "76 mi",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Vision Auto Group",
    color: "Gray",
    drivetrain: "140 hp 1.8L I4, 5-Speed Automatic",
    mpg: "Listed on CarGurus with the car",
    verdict: "Best bet",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/08/28/16/13/2012_honda_civic-pic-8600608954238043466-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/457446491",
    vin: "2HGFB2F51CH320545",
    sellerSays: "Vision Auto Group in Sugar Land, TX. 2012 Honda Civic LX. Gray. 140 hp 1.8L I4. 5-Speed Automatic. 133,500 miles. 33 days on CarGurus. Asking $7,000.",
    why: "CarGurus rates this a great price. Their estimate is $8,775, about $1,775 under that number. Ninth-generation Civic LX, regular automatic, and CarGurus has it well under their estimate.",
    watch: [
      "2012 Civic LX did not get the CVT. That is the point of picking the LX.",
      "Look at the paint in sunlight. Some Civics of this era peel on the roof and trunk.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you drive over.",
      "Ask for the out-the-door price. Doc fees can push a car in this list past $8,000.",
      "Pay for a pre-purchase inspection. A dealer lot is not the same thing as a clean mechanical bill.",
    ],
  },
  {
    id: "fit-2013-houston",
    year: 2013,
    make: "Honda",
    model: "Fit",
    trim: "Base",
    price: 7699,
    priceNote: "CarGurus estimate $8,591",
    miles: 108901,
    city: "Houston, TX",
    drive: "72 mi",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Texas Perfect Auto",
    color: "White",
    drivetrain: "117 hp 1.5L I4, Transmission was not named on the listing",
    mpg: "Listed on CarGurus with the car",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/08/07/05/45/2013_honda_fit-pic-6110712211789462106-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/455561068",
    vin: "JHMGE8H3XDC080469",
    sellerSays: "Texas Perfect Auto in Houston, TX. 2013 Honda Fit Base. White. 117 hp 1.5L I4. Transmission was not named on the listing. 108,901 miles. 54 days on CarGurus. Asking $7,699.",
    why: "CarGurus rates this a good price. Their estimate is $8,591, about $892 under that number. Lowest miles of the Fits on CarGurus in this budget, on the simple 1.5.",
    watch: [
      "The listing did not name the transmission. A 2013 Fit automatic is a regular 5-speed, not a CVT. Confirm that on the car.",
      "Spark plugs and coils come due around 100,000 miles on a Fit.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you drive over.",
      "Ask for the out-the-door price. Doc fees can push a car in this list past $8,000.",
      "Pay for a pre-purchase inspection. A dealer lot is not the same thing as a clean mechanical bill.",
    ],
  },
  {
    id: "camry-2010-spring",
    year: 2010,
    make: "Toyota",
    model: "Camry",
    trim: "LE",
    price: 7450,
    priceNote: "CarGurus estimate $7,907",
    miles: 117497,
    city: "Spring, TX",
    drive: "65 mi",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "J & M Imports",
    color: "Silver",
    drivetrain: "169 hp 2.5L I4, Automatic",
    mpg: "Listed on CarGurus with the car",
    verdict: "Best bet",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/22/13/18/2010_toyota_camry-pic-4080430774576239712-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/459592341",
    vin: "4T1BF3EK9AU027903",
    sellerSays: "J & M Imports in Spring, TX. 2010 Toyota Camry LE. Silver. 169 hp 2.5L I4. Automatic. 117,497 miles. 8 days on CarGurus. Asking $7,450.",
    why: "CarGurus rates this a good price. Their estimate is $7,907, about $457 under that number. This is the Camry generation to buy. The 2010 2.5L replaced the 2007 to 2009 2.4 that burns oil.",
    watch: [
      "117,000 miles is normal, not low. Ask for service records, especially oil changes.",
      "The price is a good rating, not a great one. You are paying for the better engine.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you drive over.",
      "Ask for the out-the-door price. Doc fees can push a car in this list past $8,000.",
      "Pay for a pre-purchase inspection. A dealer lot is not the same thing as a clean mechanical bill.",
    ],
  },
  {
    id: "civic-2011-austin",
    year: 2011,
    make: "Honda",
    model: "Civic",
    trim: "LX",
    price: 6700,
    priceNote: "CarGurus estimate $7,496",
    miles: 141233,
    city: "Austin, TX",
    drive: "90 mi",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Mazda South",
    color: "Color not listed",
    drivetrain: "140 hp 1.8L I4, 5-Speed Automatic",
    mpg: "Listed on CarGurus with the car",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/29/07/11/2011_honda_civic-pic-4629063015468637147-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/458412421",
    vin: "2HGFA1F53BH532536",
    sellerSays: "Mazda South in Austin, TX. 2011 Honda Civic LX. Color not listed. 140 hp 1.8L I4. 5-Speed Automatic. 141,233 miles. 21 days on CarGurus. Asking $6,700.",
    why: "CarGurus rates this a great price. Their estimate is $7,496, about $796 under that number. Same simple Civic formula as the Sugar Land car, at an Austin Mazda store, priced as a great deal.",
    watch: [
      "Regular 5-speed automatic. Skip it if the shifts flare.",
      "Austin is about 90 miles. Get the out-the-door number before you go.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you drive over.",
      "Ask for the out-the-door price. Doc fees can push a car in this list past $8,000.",
      "Pay for a pre-purchase inspection. A dealer lot is not the same thing as a clean mechanical bill.",
    ],
  },
  {
    id: "rav4-2012-rosenberg",
    year: 2012,
    make: "Toyota",
    model: "RAV4",
    trim: "Base",
    price: 7770,
    priceNote: "CarGurus estimate $9,987",
    miles: 144000,
    city: "Rosenberg, TX",
    drive: "79 mi",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Texas Preowned Motors",
    color: "Black",
    drivetrain: "179 hp 2.5L I4, 4-Speed Automatic",
    mpg: "Listed on CarGurus with the car",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/27/04/52/2012_toyota_rav4-pic-8359192445651925404-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/457768261",
    vin: "2T3ZF4DV1CW122806",
    sellerSays: "Texas Preowned Motors in Rosenberg, TX. 2012 Toyota RAV4 Base. Black. 179 hp 2.5L I4. 4-Speed Automatic. 144,000 miles. 29 days on CarGurus. Asking $7,770.",
    why: "CarGurus rates this a great price. Their estimate is $9,987, about $2,217 under that number. 2012 RAV4 with the 2.5 four-cylinder, which is the durable one, and a great-price rating.",
    watch: [
      "It uses more gas than the sedans. Worth it if you want the space.",
      "This one is front-wheel drive. The Sugar Land car is the 4WD if you need that.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you drive over.",
      "Ask for the out-the-door price. Doc fees can push a car in this list past $8,000.",
      "Pay for a pre-purchase inspection. A dealer lot is not the same thing as a clean mechanical bill.",
    ],
  },
  {
    id: "civic-2009-houston",
    year: 2009,
    make: "Honda",
    model: "Civic",
    trim: "LX",
    price: 6499,
    priceNote: "CarGurus estimate $7,100",
    miles: 129825,
    city: "Houston, TX",
    drive: "80 mi",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Auto Ride",
    color: "Red",
    drivetrain: "140 hp 1.8L I4, 5-Speed Automatic Overdrive",
    mpg: "Listed on CarGurus with the car",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/08/01/03/22/2009_honda_civic-pic-646474522501304399-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/454962973",
    vin: "2HGFA16529H534675",
    sellerSays: "Auto Ride in Houston, TX. 2009 Honda Civic LX. Red. 140 hp 1.8L I4. 5-Speed Automatic Overdrive. 129,825 miles. 60 days on CarGurus. Asking $6,499.",
    why: "CarGurus rates this a good price. Their estimate is $7,100, about $601 under that number. Eighth-generation Civic LX, regular automatic, good-price rating, in Houston.",
    watch: [
      "2006 to 2011 Civic paint can peel. Check the roof and trunk in the sun.",
      "Engine mounts on this generation crack. In drive, with the brake on, the engine should not rock.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you drive over.",
      "Ask for the out-the-door price. Doc fees can push a car in this list past $8,000.",
      "Pay for a pre-purchase inspection. A dealer lot is not the same thing as a clean mechanical bill.",
    ],
  },
  {
    id: "accord-2008-houston",
    year: 2008,
    make: "Honda",
    model: "Accord",
    trim: "EX-L",
    price: 6600,
    priceNote: "CarGurus estimate $7,181",
    miles: 130754,
    city: "Houston, TX",
    drive: "81 mi",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Enterprise Motors Car Inc",
    color: "BLACK",
    drivetrain: "177 hp 2.4L I4, Automatic",
    mpg: "Listed on CarGurus with the car",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/05/11/52/2008_honda_accord-pic-4380754853118914270-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/458219482",
    vin: "1HGCP26868A069915",
    sellerSays: "Enterprise Motors Car Inc in Houston, TX. 2008 Honda Accord EX-L. BLACK. 177 hp 2.4L I4. Automatic. 130,754 miles. 25 days on CarGurus. Asking $6,600.",
    why: "CarGurus rates this a good price. Their estimate is $7,181, about $581 under that number. Four-cylinder EX-L, regular automatic, leather, good-price rating. The V6 Accords were left off because they need a timing belt.",
    watch: [
      "2008 to 2012 four-cylinder Accords can tick on a cold start. That is usually the VTC actuator.",
      "Some of these engines use oil. Check the dipstick before you decide the miles are fine.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you drive over.",
      "Ask for the out-the-door price. Doc fees can push a car in this list past $8,000.",
      "Pay for a pre-purchase inspection. A dealer lot is not the same thing as a clean mechanical bill.",
    ],
  },
  {
    id: "corolla-2013-houston",
    year: 2013,
    make: "Toyota",
    model: "Corolla",
    trim: "LE",
    price: 7995,
    priceNote: "CarGurus estimate $9,055",
    miles: 124401,
    city: "Houston, TX",
    drive: "77 mi",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Drive 4 Less Auto Sales",
    color: "Gray",
    drivetrain: "132 hp 1.8L I4, 4-Speed Automatic",
    mpg: "Listed on CarGurus with the car",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/25/04/22/2013_toyota_corolla-pic-625812036988172734-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/459881565",
    vin: "5YFBU4EE1DP083068",
    sellerSays: "Drive 4 Less Auto Sales in Houston, TX. 2013 Toyota Corolla LE. Gray. 132 hp 1.8L I4. 4-Speed Automatic. 124,401 miles. 5 days on CarGurus. Asking $7,995.",
    why: "CarGurus rates this a good price. Their estimate is $9,055, about $1,060 under that number. A 2013 Corolla with 124,000 miles is newer than most of this budget, and the 1.8 is still the simple one.",
    watch: [
      "It is at the ceiling of the budget before dealer fees. Ask for the out-the-door price.",
      "4-speed automatic. It should shift without flaring.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you drive over.",
      "Ask for the out-the-door price. Doc fees can push a car in this list past $8,000.",
      "Pay for a pre-purchase inspection. A dealer lot is not the same thing as a clean mechanical bill.",
    ],
  },
  {
    id: "rav4-2012-sugar-land",
    year: 2012,
    make: "Toyota",
    model: "RAV4",
    trim: "Base 4WD",
    price: 7500,
    priceNote: "CarGurus estimate $9,593",
    miles: 145000,
    city: "Sugar Land, TX",
    drive: "76 mi",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Vision Auto Group",
    color: "Black",
    drivetrain: "179 hp 2.5L I4, 4-Speed Automatic",
    mpg: "Listed on CarGurus with the car",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/08/25/04/07/2012_toyota_rav4-pic-940073622047564934-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/453529459",
    vin: "JTMBF4DVXCD043827",
    sellerSays: "Vision Auto Group in Sugar Land, TX. 2012 Toyota RAV4 Base 4WD. Black. 179 hp 2.5L I4. 4-Speed Automatic. 145,000 miles. 76 days on CarGurus. Asking $7,500.",
    why: "CarGurus rates this a great price. Their estimate is $9,593, about $2,093 under that number. The all-wheel-drive version of the same 2012 RAV4, also a great price, in Sugar Land.",
    watch: [
      "4WD adds tires and a bit of maintenance. Make sure it engages and that the tires match.",
      "145,000 miles is a lot of heat cycles. Service records matter more than the badge.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you drive over.",
      "Ask for the out-the-door price. Doc fees can push a car in this list past $8,000.",
      "Pay for a pre-purchase inspection. A dealer lot is not the same thing as a clean mechanical bill.",
    ],
  },
  {
    id: "crv-2011-houston",
    year: 2011,
    make: "Honda",
    model: "CR-V",
    trim: "EX FWD",
    price: 7990,
    priceNote: "CarGurus estimate $8,491",
    miles: 147000,
    city: "Houston, TX",
    drive: "69 mi",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Executive Motor Group LLC.",
    color: "BLUE",
    drivetrain: "180 hp 2.4L I4, Automatic",
    mpg: "Listed on CarGurus with the car",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/16/10/54/2011_honda_cr-v-pic-8812423676519461840-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/459001296",
    vin: "5J6RE3H58BL006750",
    sellerSays: "Executive Motor Group LLC. in Houston, TX. 2011 Honda CR-V EX FWD. BLUE. 180 hp 2.4L I4. Automatic. 147,000 miles. 14 days on CarGurus. Asking $7,990.",
    why: "CarGurus rates this a good price. Their estimate is $8,491, about $501 under that number. 2011 CR-V EX, four-cylinder, good price, about 69 miles away.",
    watch: [
      "2007 to 2011 CR-V air-conditioner compressors fail often, and the repair is commonly over $1,000. Run the A/C on max.",
      "EX means more equipment to check: sunroof drains, leather or cloth wear, and the rear hatch.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you drive over.",
      "Ask for the out-the-door price. Doc fees can push a car in this list past $8,000.",
      "Pay for a pre-purchase inspection. A dealer lot is not the same thing as a clean mechanical bill.",
    ],
  },
  {
    id: "corolla-2009-killeen",
    year: 2009,
    make: "Toyota",
    model: "Corolla",
    trim: "Base",
    price: 6990,
    priceNote: "CarGurus estimate $8,662",
    miles: 123394,
    city: "Killeen, TX",
    drive: "87 mi",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Airport Auto Sales",
    color: "Gray",
    drivetrain: "132 hp 1.8L I4, Automatic",
    mpg: "Listed on CarGurus with the car",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/22/13/16/2009_toyota_corolla-pic-5706535215391115161-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/459592330",
    vin: "JTDBL40E499021476",
    sellerSays: "Airport Auto Sales in Killeen, TX. 2009 Toyota Corolla Base. Gray. 132 hp 1.8L I4. Automatic. 123,394 miles. 8 days on CarGurus. Asking $6,990.",
    why: "CarGurus rates this a great price. Their estimate is $8,662, about $1,672 under that number. Another 1.8 Corolla that CarGurus marks a great price, this one in Killeen.",
    watch: [
      "Killeen is about 87 miles. The Spring Corolla is cheaper and a bit closer if both are still up.",
      "Base trim. You are buying the engine, not the options.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you drive over.",
      "Ask for the out-the-door price. Doc fees can push a car in this list past $8,000.",
      "Pay for a pre-purchase inspection. A dealer lot is not the same thing as a clean mechanical bill.",
    ],
  },
  {
    id: "accord-2012-spring",
    year: 2012,
    make: "Honda",
    model: "Accord",
    trim: "EX-L",
    price: 6799,
    priceNote: "CarGurus estimate $8,811",
    miles: 165822,
    city: "Spring, TX",
    drive: "61 mi",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "iST Motors",
    color: "Color not listed",
    drivetrain: "190 hp 2.4L I4, 5-Speed Automatic",
    mpg: "Listed on CarGurus with the car",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/01/12/15/2012_honda_accord-pic-8184156787471264215-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/455419120",
    vin: "1HGCP2F87CA098655",
    sellerSays: "iST Motors in Spring, TX. 2012 Honda Accord EX-L. Color not listed. 190 hp 2.4L I4. 5-Speed Automatic. 165,822 miles. 55 days on CarGurus. Asking $6,799.",
    why: "CarGurus rates this a great price. Their estimate is $8,811, about $2,012 under that number. 2012 Accord EX-L, four-cylinder, 5-speed automatic, great-price rating, only 61 miles away.",
    watch: [
      "165,000 miles is the trade. The engine family is right. The service history has to be right too.",
      "Cold-start tick and oil use are the two things to listen and look for.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you drive over.",
      "Ask for the out-the-door price. Doc fees can push a car in this list past $8,000.",
      "Pay for a pre-purchase inspection. A dealer lot is not the same thing as a clean mechanical bill.",
    ],
  },
  {
    id: "crv-2013-jersey-village",
    year: 2013,
    make: "Honda",
    model: "CR-V",
    trim: "LX FWD",
    price: 7999,
    priceNote: "CarGurus estimate $9,441",
    miles: 154104,
    city: "Jersey Village, TX",
    drive: "67 mi",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "MSM Auto Group",
    color: "Blue",
    drivetrain: "185 hp 2.4L I4, 5-Speed Automatic",
    mpg: "Listed on CarGurus with the car",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/08/31/16/17/2013_honda_cr-v-pic-2095600534665365167-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/457663395",
    vin: "2HKRM3H36DH501138",
    sellerSays: "MSM Auto Group in Jersey Village, TX. 2013 Honda CR-V LX FWD. Blue. 185 hp 2.4L I4. 5-Speed Automatic. 154,104 miles. 30 days on CarGurus. Asking $7,999.",
    why: "CarGurus rates this a great price. Their estimate is $9,441, about $1,442 under that number. Great-price 2013 CR-V, 67 miles away, at a dealer that also has one of the Camrys.",
    watch: [
      "154,000 miles. Budget tires, brakes, and a transmission service if the records are thin.",
      "Run the A/C. Even the newer CR-Vs are not immune, and Houston heat shows it.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you drive over.",
      "Ask for the out-the-door price. Doc fees can push a car in this list past $8,000.",
      "Pay for a pre-purchase inspection. A dealer lot is not the same thing as a clean mechanical bill.",
    ],
  },
  {
    id: "camry-2016-san-antonio",
    year: 2016,
    make: "Toyota",
    model: "Camry",
    trim: "LE",
    price: 7500,
    priceNote: "CarGurus estimate $9,326",
    miles: 172342,
    city: "San Antonio, TX",
    drive: "159 mi",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "usave car sales",
    color: "Black",
    drivetrain: "178 hp 2.5L I4, 6-Speed Automatic",
    mpg: "Listed on CarGurus with the car",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/18/21/48/2016_toyota_camry-pic-3978736195748188345-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/459339245",
    vin: "4T4BF1FK4GR564759",
    sellerSays: "usave car sales in San Antonio, TX. 2016 Toyota Camry LE. Black. 178 hp 2.5L I4. 6-Speed Automatic. 172,342 miles. 12 days on CarGurus. Asking $7,500.",
    why: "CarGurus rates this a great price. Their estimate is $9,326, about $1,826 under that number. Newest Camry in the budget: a 2016 with the 2.5 and a 6-speed automatic, marked a great price.",
    watch: [
      "172,000 miles is why it is $7,500. Do not treat a 2016 badge as low miles.",
      "San Antonio is about 159 miles. Confirm it is still for sale before the drive.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you drive over.",
      "Ask for the out-the-door price. Doc fees can push a car in this list past $8,000.",
      "Pay for a pre-purchase inspection. A dealer lot is not the same thing as a clean mechanical bill.",
    ],
  },
  {
    id: "fit-2015-buda",
    year: 2015,
    make: "Honda",
    model: "Fit",
    trim: "LX",
    price: 7695,
    priceNote: "CarGurus estimate $8,065",
    miles: 145985,
    city: "Buda, TX",
    drive: "96 mi",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Hatimi Auto LLC",
    color: "Black",
    drivetrain: "130 hp 1.5L I4, Continuously Variable Transmission",
    mpg: "Listed on CarGurus with the car",
    verdict: "Check first",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/07/27/17/11/2015_honda_fit-pic-1335463826568368345-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/452921274",
    vin: "3HGGK5H51FM716015",
    sellerSays: "Hatimi Auto LLC in Buda, TX. 2015 Honda Fit LX. Black. 130 hp 1.5L I4. Continuously Variable Transmission. 145,985 miles. 84 days on CarGurus. Asking $7,695.",
    why: "CarGurus rates this a good price. Their estimate is $8,065, about $370 under that number. A newer Fit, but the transmission is the thing to decide on, not the badge.",
    watch: [
      "Listen for CVT shudder leaving a light and on a slow roll.",
      "Buda is south of Austin, about 96 miles.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you drive over.",
      "Ask for the out-the-door price. Doc fees can push a car in this list past $8,000.",
      "Pay for a pre-purchase inspection. A dealer lot is not the same thing as a clean mechanical bill.",
    ],
  },
  {
    id: "accord-2015-sugar-land",
    year: 2015,
    make: "Honda",
    model: "Accord",
    trim: "LX",
    price: 7400,
    priceNote: "CarGurus estimate $9,030",
    miles: 175700,
    city: "Sugar Land, TX",
    drive: "76 mi",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "HK AUTOS",
    color: "Obsidian Blue Pearl",
    drivetrain: "185 hp 2.4L I4, Continuously Variable Transmission",
    mpg: "Listed on CarGurus with the car",
    verdict: "Check first",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/25/04/22/2015_honda_accord-pic-1640636138404875848-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/459881793",
    vin: "1HGCR2F31FA056131",
    sellerSays: "HK AUTOS in Sugar Land, TX. 2015 Honda Accord LX. Obsidian Blue Pearl. 185 hp 2.4L I4. Continuously Variable Transmission. 175,700 miles. 5 days on CarGurus. Asking $7,400.",
    why: "CarGurus rates this a great price. Their estimate is $9,030, about $1,630 under that number. A 2015 Accord at a great-price rating. Newer than the 2008 to 2012 cars, with the CVT those cars did not have.",
    watch: [
      "Shudder or a flare off the line is a no.",
      "175,000 miles on a CVT needs records of fluid changes, not just an oil sticker.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you drive over.",
      "Ask for the out-the-door price. Doc fees can push a car in this list past $8,000.",
      "Pay for a pre-purchase inspection. A dealer lot is not the same thing as a clean mechanical bill.",
    ],
  },
  {
    id: "camry-2008-nederland",
    year: 2008,
    make: "Toyota",
    model: "Camry",
    trim: "LE",
    price: 5219,
    priceNote: "CarGurus estimate $9,041",
    miles: 102154,
    city: "Nederland, TX",
    drive: "144 mi",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Philpott Toyota",
    color: "Color not listed",
    drivetrain: "158 hp 2.4L I4, Automatic",
    mpg: "Listed on CarGurus with the car",
    verdict: "Check first",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/25/13/54/2008_toyota_camry-pic-8962053650554632967-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/459531975",
    vin: "4T1BE46K78U216048",
    sellerSays: "Philpott Toyota in Nederland, TX. 2008 Toyota Camry LE. Color not listed. 158 hp 2.4L I4. Automatic. 102,154 miles. 8 days on CarGurus. Asking $5,219.",
    why: "CarGurus rates this a great price. Their estimate is $9,041, about $3,822 under that number. Philpott Toyota has the lowest miles in this whole pull, at $5,219, and CarGurus is far above that on the estimate. The engine year is why it is not first.",
    watch: [
      "Check the dipstick cold, then again after a drive. Ask how often they add oil.",
      "Nederland is about 144 miles, past Houston. A Toyota store is a better counterparty than a curb ad. It does not fix an oil-burner.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you drive over.",
      "Ask for the out-the-door price. Doc fees can push a car in this list past $8,000.",
      "Pay for a pre-purchase inspection. A dealer lot is not the same thing as a clean mechanical bill.",
    ],
  },
  {
    id: "camry-2009-jersey-village",
    year: 2009,
    make: "Toyota",
    model: "Camry",
    trim: "XLE",
    price: 6499,
    priceNote: "CarGurus estimate $7,869",
    miles: 105658,
    city: "Jersey Village, TX",
    drive: "67 mi",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "MSM Auto Group",
    color: "Super White",
    drivetrain: "158 hp 2.4L I4, 5-Speed Automatic",
    mpg: "Listed on CarGurus with the car",
    verdict: "Check first",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/26/05/19/2009_toyota_camry-pic-5399510397861382211-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/460010534",
    vin: "4T4BE46K29R070276",
    sellerSays: "MSM Auto Group in Jersey Village, TX. 2009 Toyota Camry XLE. Super White. 158 hp 2.4L I4. 5-Speed Automatic. 105,658 miles. 4 days on CarGurus. Asking $6,499.",
    why: "CarGurus rates this a great price. Their estimate is $7,869, about $1,370 under that number. 105,000 miles and a great-price rating in Jersey Village. Pretty miles on the wrong Camry year.",
    watch: [
      "Blue smoke on startup and a low dipstick are the walk-away signs.",
      "XLE means more power equipment to test, not a different engine.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you drive over.",
      "Ask for the out-the-door price. Doc fees can push a car in this list past $8,000.",
      "Pay for a pre-purchase inspection. A dealer lot is not the same thing as a clean mechanical bill.",
    ],
  },
  {
    id: "crv-2007-dallas",
    year: 2007,
    make: "Honda",
    model: "CR-V",
    trim: "LX FWD",
    price: 7250,
    priceNote: "CarGurus estimate $7,742",
    miles: 124015,
    city: "Dallas, TX",
    drive: "163 mi",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Image Auto Sales",
    color: "Black",
    drivetrain: "166 hp 2.4L I4, 5-Speed Automatic",
    mpg: "Listed on CarGurus with the car",
    verdict: "Check first",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/10/04/06/2007_honda_cr-v-pic-2536561652717616188-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/458499395",
    vin: "JHLRE38357C024847",
    sellerSays: "Image Auto Sales in Dallas, TX. 2007 Honda CR-V LX FWD. Black. 166 hp 2.4L I4. 5-Speed Automatic. 124,015 miles. 20 days on CarGurus. Asking $7,250.",
    why: "CarGurus rates this a good price. Their estimate is $7,742, about $492 under that number. 2007 CR-V with the tough 2.4 and a regular automatic. Dallas is the long end of this list.",
    watch: [
      "The A/C compressor on this generation is the known four-figure repair. Ten minutes on max, in the sun.",
      "163 miles is a long way to discover a weak compressor. Ask them to send a video of the A/C blowing cold.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you drive over.",
      "Ask for the out-the-door price. Doc fees can push a car in this list past $8,000.",
      "Pay for a pre-purchase inspection. A dealer lot is not the same thing as a clean mechanical bill.",
    ],
  },
  {
    id: "fit-2011-lavon",
    year: 2011,
    make: "Honda",
    model: "Fit",
    trim: "Sport",
    price: 6600,
    priceNote: "CarGurus estimate $7,025",
    miles: 152425,
    city: "Lavon, TX",
    drive: "166 mi",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "DriveLine Auto Solution",
    color: "White",
    drivetrain: "117 hp 1.5L I4, 5-Speed Automatic Overdrive",
    mpg: "Listed on CarGurus with the car",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/08/01/12/06/2011_honda_fit-pic-144544649112331122-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/454952781",
    vin: "JHMGE8H50BC001888",
    sellerSays: "DriveLine Auto Solution in Lavon, TX. 2011 Honda Fit Sport. White. 117 hp 1.5L I4. 5-Speed Automatic Overdrive. 152,425 miles. 60 days on CarGurus. Asking $6,600.",
    why: "CarGurus rates this a good price. Their estimate is $7,025, about $425 under that number. A Fit with a real 5-speed automatic and a good-price rating, if the Houston cars are gone.",
    watch: [
      "Lavon is northeast of Dallas, about 166 miles.",
      "152,000 miles on a Fit is acceptable only if it has been serviced. Coils and plugs are due.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you drive over.",
      "Ask for the out-the-door price. Doc fees can push a car in this list past $8,000.",
      "Pay for a pre-purchase inspection. A dealer lot is not the same thing as a clean mechanical bill.",
    ],
  },
  {
    id: "rav4-2008-brookshire",
    year: 2008,
    make: "Toyota",
    model: "RAV4",
    trim: "Limited",
    price: 6995,
    priceNote: "CarGurus estimate $8,566",
    miles: 151835,
    city: "Brookshire, TX",
    drive: "57 mi",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Brookshire Hyundai",
    color: "Barcelona Red Metallic",
    drivetrain: "166 hp 2.4L I4, 5-Speed Automatic",
    mpg: "Listed on CarGurus with the car",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/26/07/16/2008_toyota_rav4-pic-1757938314996047203-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/460032114",
    vin: "JTMZK31V385022053",
    sellerSays: "Brookshire Hyundai in Brookshire, TX. 2008 Toyota RAV4 Limited. Barcelona Red Metallic. 166 hp 2.4L I4. 5-Speed Automatic. 151,835 miles. 4 days on CarGurus. Asking $6,995.",
    why: "CarGurus rates this a great price. Their estimate is $8,566, about $1,571 under that number. Great-price RAV4 at Brookshire Hyundai, 57 miles away, four days on the site.",
    watch: [
      "Limited trim. Test the leather, the sunroof, and the 4-cylinder cold start.",
      "151,000 miles. New listing, so go soon, and still get an inspection.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you drive over.",
      "Ask for the out-the-door price. Doc fees can push a car in this list past $8,000.",
      "Pay for a pre-purchase inspection. A dealer lot is not the same thing as a clean mechanical bill.",
    ],
  },
];
