export type Seller = 'Dealer';
export type Car = {
  id: string;
  year: number;
  make: string;
  model: string;
  trim: string;
  price: number;
  priceNote: string;
  miles: number;
  city: string;
  drive: string;
  owners: string;
  title: string;
  seller: Seller;
  dealer: string;
  color: string;
  drivetrain: string;
  mpg: string;
  verdict: string;
  photos: string[];
  listingUrl: string;
  vin: string;
  sellerSays: string;
  why: string;
  watch: string[];
  check: string[];
};

export type YearGrade = 'better' | 'typical' | 'worse';

export type YearRecord = {
  grade: YearGrade;
  note: string;
};

/** Complaint-year check, same idea as carbuyer-ontario. Not a Texas price. */
export const YEAR_RECORDS: Record<string, YearRecord> = {
  "civic-2009-katy": { grade: "typical", note: "Normal complaint volume for this Civic era. The common theme is airbags, not the 1.8." },
  "civic-2008-college-station": { grade: "typical", note: "Normal complaint volume. Airbags are the common theme on this Civic generation." },
  "civic-2012-sugar-land": { grade: "typical", note: "Normal Civic volume. This 2012 LX still has a regular 5-speed automatic, not a CVT." },
  "rav4-2012-katy": { grade: "typical", note: "Normal RAV4 complaint volume. The 2.5 in this 2012 is the durable engine." },
  "rav4-2008-richmond": { grade: "typical", note: "Normal volume for this older RAV4. The 2.4 is not the Camry oil story, and the dipstick still matters." },
  "rav4-2008-brookshire": { grade: "typical", note: "Ordinary complaint volume. Wipers show up more than engine failures on these RAV4s." },
  "rav4-2012-rosenberg": { grade: "typical", note: "The 2012 RAV4 2.5 has an ordinary complaint record. Wipers, not the engine." },
  "rav4-2012-sugar-land": { grade: "typical", note: "Same 2012 RAV4 record. The 2.5 is the one you want." },
  "camry-2010-sugar-land": { grade: "typical", note: "This is the 2.5L Camry, the one that replaced the oil-burning 2.4. Complaint volume is normal." },
  "fit-2013-houston": { grade: "typical", note: "Normal Fit complaint volume. Airbags are the common theme." },
  "corolla-2013-houston": { grade: "better", note: "Fewer complaints than nearby Corolla years." },
  "civic-2009-houston": { grade: "typical", note: "Normal Civic volume for 2009. Airbags are the common theme." },
  "accord-2008-houston": { grade: "better", note: "Fewer complaints than the Accord years around it. Seats, not the engine." },
  "corolla-2011-houston": { grade: "typical", note: "Normal Corolla volume. The 1.8 is the simple motor." },
  "civic-2008-houston": { grade: "typical", note: "Normal volume for a 2008 Civic." },
  "crv-2011-houston": { grade: "typical", note: "Normal CR-V volume. Airbags, not the 2.4." },
  "camry-2009-houston": { grade: "worse", note: "The 2007 to 2009 Camry 2.4 draws about three times the complaints of nearby years. Brakes are the headline. Oil use is the other bill." },
  "corolla-2013-houston-direct": { grade: "better", note: "Fewer complaints than nearby Corolla years." },
  "fit-2012-houston": { grade: "typical", note: "Normal Fit volume. This 2012 still uses a regular automatic." },
  "accord-2015-sugar-land": { grade: "typical", note: "2013 and newer Accord automatics are CVTs. Complaint volume is ordinary. The transmission is the question." },
};

export const CHECKED_ON = 'September 30, 2026';

export const MARKET_NOTES = [
  "Every car is a dealer listing on CarGurus. It has to be about 30 minutes from Texas A&M, about 30 minutes from Seven Lakes High School in Katy, or in Houston. Dallas, Austin, San Antonio, and Spring are not on this deck.",
  "College Station only had one Honda or Toyota in the $5,000 to $8,000 band: a 2008 Civic at Allen Honda. The rest of the close cars are in Katy, Brookshire, Richmond, Rosenberg, and Sugar Land. Houston is included because you said the city is fine.",
  "Jersey Village calculated to about 34 minutes from Seven Lakes, so those cars stayed off. A 2009 Camry XLE there was the best miles in the pull. It is over your line.",
  "CarGurus great price means the ask is under their estimate. It does not include dealer fees, and it does not mean the car is low miles. Ask for the out-the-door number.",
  "The 2007 to 2009 Camry 2.4 still burns oil, so the one Houston example is marked check first. V6 Accords are not here. 2015 Accord automatics in this list use a CVT.",
  "The Board still uses the complaint-year check from carbuyer-ontario. Those prices are Canadian and in Ontario, so they are not used as a Texas bargain score.",
  "No used car is guaranteed. A pre-purchase inspection, about $150 to $200, is the check that matters. Read the history report on the VIN yourself.",
];

export const CARS: Car[] = [
  {
    id: "civic-2009-katy",
    year: 2009,
    make: "Honda",
    model: "Civic",
    trim: "LX",
    price: 7673,
    priceNote: "CarGurus estimate $7,279",
    miles: 126201,
    city: "Katy, TX",
    drive: "about 10 min from Seven Lakes",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "AutoNation Chrysler Dodge Jeep Ram Katy",
    color: "Atomic Blue Metall",
    drivetrain: "140 hp 1.8L I4, 5-Speed Automatic",
    mpg: "",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/16/17/45/2009_honda_civic-pic-7858585730077920167-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/459075638",
    vin: "19XFA16569E052270",
    sellerSays: "AutoNation Chrysler Dodge Jeep Ram Katy in Katy, TX. 2009 Honda Civic LX. Atomic Blue Metall. 140 hp 1.8L I4. 5-Speed Automatic. 126,201 miles. 14 days on CarGurus. Asking $7,673.",
    why: "CarGurus rates this a fair price. CarGurus estimate $7,279, about $394 over that. This is the one next to Seven Lakes. AutoNation in Katy, about 10 minutes from the school, 126,000 miles.",
    watch: [
      "The asking price sits a bit over the CarGurus estimate, which is why the rating is fair, not great.",
      "Regular 5-speed automatic. It should shift without flaring.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you go.",
      "Ask for the out-the-door price. Fees can push these past $8,000.",
      "Get a pre-purchase inspection. A dealer lot is not a mechanical guarantee.",
    ],
  },
  {
    id: "civic-2008-college-station",
    year: 2008,
    make: "Honda",
    model: "Civic",
    trim: "LX",
    price: 6500,
    priceNote: "CarGurus estimate $6,608",
    miles: 166648,
    city: "College Station, TX",
    drive: "about 2 min from Texas A&M",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Allen Honda",
    color: "GRAY",
    drivetrain: "140 hp 1.8L I4, Automatic",
    mpg: "",
    verdict: "Check first",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/08/26/03/10/2008_honda_civic-pic-1937963070748687821-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/457026969",
    vin: "2HGFA165X8H342712",
    sellerSays: "Allen Honda in College Station, TX. 2008 Honda Civic LX. GRAY. 140 hp 1.8L I4. Automatic. 166,648 miles. 36 days on CarGurus. Asking $6,500.",
    why: "CarGurus rates this a fair price. CarGurus estimate $6,608, about $108 under that. This is the campus car. Allen Honda in College Station, about 2 minutes from Texas A&M.",
    watch: [
      "166,000 miles is the reason to be picky. The location is the reason it is on the deck.",
      "It is a fair price, basically on the CarGurus estimate, not a steal.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you go.",
      "Ask for the out-the-door price. Fees can push these past $8,000.",
      "Get a pre-purchase inspection. A dealer lot is not a mechanical guarantee.",
    ],
  },
  {
    id: "civic-2012-sugar-land",
    year: 2012,
    make: "Honda",
    model: "Civic",
    trim: "LX",
    price: 7000,
    priceNote: "CarGurus estimate $8,775",
    miles: 133500,
    city: "Sugar Land, TX",
    drive: "about 28 min from Seven Lakes",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Vision Auto Group",
    color: "Gray",
    drivetrain: "140 hp 1.8L I4, 5-Speed Automatic",
    mpg: "",
    verdict: "Best bet",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/08/28/16/13/2012_honda_civic-pic-8600608954238043466-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/457446491",
    vin: "2HGFB2F51CH320545",
    sellerSays: "Vision Auto Group in Sugar Land, TX. 2012 Honda Civic LX. Gray. 140 hp 1.8L I4. 5-Speed Automatic. 133,500 miles. 33 days on CarGurus. Asking $7,000.",
    why: "CarGurus rates this a great price. CarGurus estimate $8,775, about $1,775 under that. About 28 minutes from Seven Lakes, and CarGurus marks it a great price.",
    watch: [
      "Sugar Land is inside the 30-minute line. Confirm the out-the-door number before you go.",
      "Check the paint on the roof and trunk.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you go.",
      "Ask for the out-the-door price. Fees can push these past $8,000.",
      "Get a pre-purchase inspection. A dealer lot is not a mechanical guarantee.",
    ],
  },
  {
    id: "rav4-2012-katy",
    year: 2012,
    make: "Toyota",
    model: "RAV4",
    trim: "Base",
    price: 7999,
    priceNote: "No CarGurus estimate",
    miles: 165600,
    city: "Katy, TX",
    drive: "about 10 min from Seven Lakes",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Avantgarde USA LLC",
    color: "Gold",
    drivetrain: "179 hp 2.5L I4, Automatic",
    mpg: "",
    verdict: "Check first",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/15/07/36/2012_toyota_rav4-pic-6400759244687213845-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/458935443",
    vin: "JTMZF4DV6CD031768",
    sellerSays: "Avantgarde USA LLC in Katy, TX. 2012 Toyota RAV4 Base. Gold. 179 hp 2.5L I4. Automatic. 165,600 miles. 15 days on CarGurus. Asking $7,999.",
    why: "CarGurus rates this unscored. CarGurus did not publish an estimate. In Katy, about 10 minutes from Seven Lakes. CarGurus did not publish a deal score.",
    watch: [
      "165,000 miles and no deal score. Go because it is close, and get an inspection before you pay.",
      "It is at the top of the budget before fees.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you go.",
      "Ask for the out-the-door price. Fees can push these past $8,000.",
      "Get a pre-purchase inspection. A dealer lot is not a mechanical guarantee.",
    ],
  },
  {
    id: "rav4-2008-richmond",
    year: 2008,
    make: "Toyota",
    model: "RAV4",
    trim: "Limited",
    price: 7500,
    priceNote: "CarGurus estimate $6,733",
    miles: 167883,
    city: "Richmond, TX",
    drive: "about 23 min from Seven Lakes",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Group 1 Toyota Fort Bend",
    color: "Barcelona Red Metallic",
    drivetrain: "166 hp 2.4L I4, 4-Speed Automatic",
    mpg: "",
    verdict: "Check first",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/17/08/40/2008_toyota_rav4-pic-7262811619923711746-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/458876470",
    vin: "JTMZD31V086079685",
    sellerSays: "Group 1 Toyota Fort Bend in Richmond, TX. 2008 Toyota RAV4 Limited. Barcelona Red Metallic. 166 hp 2.4L I4. 4-Speed Automatic. 167,883 miles. 16 days on CarGurus. Asking $7,500.",
    why: "CarGurus rates this a fair price. CarGurus estimate $6,733, about $767 over that. Group 1 Toyota in Richmond, about 23 minutes from Seven Lakes. A real Toyota store.",
    watch: [
      "The ask is over the CarGurus estimate, and it has 167,000 miles. You are paying for the dealer, not a bargain.",
      "Limited trim: test the sunroof and the leather.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you go.",
      "Ask for the out-the-door price. Fees can push these past $8,000.",
      "Get a pre-purchase inspection. A dealer lot is not a mechanical guarantee.",
    ],
  },
  {
    id: "rav4-2008-brookshire",
    year: 2008,
    make: "Toyota",
    model: "RAV4",
    trim: "Limited",
    price: 7032,
    priceNote: "CarGurus estimate $8,566",
    miles: 151835,
    city: "Brookshire, TX",
    drive: "about 24 min from Seven Lakes",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Brookshire Hyundai",
    color: "Barcelona Red Metallic",
    drivetrain: "166 hp 2.4L I4, 5-Speed Automatic",
    mpg: "",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/26/07/16/2008_toyota_rav4-pic-1757938314996047203-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/460032114",
    vin: "JTMZK31V385022053",
    sellerSays: "Brookshire Hyundai in Brookshire, TX. 2008 Toyota RAV4 Limited. Barcelona Red Metallic. 166 hp 2.4L I4. 5-Speed Automatic. 151,835 miles. 4 days on CarGurus. Asking $7,032.",
    why: "CarGurus rates this a great price. CarGurus estimate $8,566, about $1,534 under that. Brookshire Hyundai, about 24 minutes from Seven Lakes, and CarGurus calls it a great price.",
    watch: [
      "151,000 miles, four days on the site. Go soon, then still inspect it.",
      "Limited trim. Cold start and the dipstick.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you go.",
      "Ask for the out-the-door price. Fees can push these past $8,000.",
      "Get a pre-purchase inspection. A dealer lot is not a mechanical guarantee.",
    ],
  },
  {
    id: "rav4-2012-rosenberg",
    year: 2012,
    make: "Toyota",
    model: "RAV4",
    trim: "Base",
    price: 7770,
    priceNote: "CarGurus estimate $9,987",
    miles: 144000,
    city: "Rosenberg, TX",
    drive: "about 27 min from Seven Lakes",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Texas Preowned Motors",
    color: "Black",
    drivetrain: "179 hp 2.5L I4, 4-Speed Automatic",
    mpg: "",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/27/04/52/2012_toyota_rav4-pic-8359192445651925404-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/457768261",
    vin: "2T3ZF4DV1CW122806",
    sellerSays: "Texas Preowned Motors in Rosenberg, TX. 2012 Toyota RAV4 Base. Black. 179 hp 2.5L I4. 4-Speed Automatic. 144,000 miles. 29 days on CarGurus. Asking $7,770.",
    why: "CarGurus rates this a great price. CarGurus estimate $9,987, about $2,217 under that. Rosenberg, about 27 minutes from Seven Lakes. Great price against a CarGurus estimate near $10,000.",
    watch: [
      "Front-wheel drive. The Sugar Land one is the 4WD if you need it.",
      "It drinks more gas than the Civics.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you go.",
      "Ask for the out-the-door price. Fees can push these past $8,000.",
      "Get a pre-purchase inspection. A dealer lot is not a mechanical guarantee.",
    ],
  },
  {
    id: "rav4-2012-sugar-land",
    year: 2012,
    make: "Toyota",
    model: "RAV4",
    trim: "Base 4WD",
    price: 7500,
    priceNote: "CarGurus estimate $9,593",
    miles: 145000,
    city: "Sugar Land, TX",
    drive: "about 28 min from Seven Lakes",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Vision Auto Group",
    color: "Black",
    drivetrain: "179 hp 2.5L I4, 4-Speed Automatic",
    mpg: "",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/08/25/04/07/2012_toyota_rav4-pic-940073622047564934-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/453529459",
    vin: "JTMBF4DVXCD043827",
    sellerSays: "Vision Auto Group in Sugar Land, TX. 2012 Toyota RAV4 Base 4WD. Black. 179 hp 2.5L I4. 4-Speed Automatic. 145,000 miles. 76 days on CarGurus. Asking $7,500.",
    why: "CarGurus rates this a great price. CarGurus estimate $9,593, about $2,093 under that. 4WD version in Sugar Land, about 28 minutes from Seven Lakes, also a great price.",
    watch: [
      "Match the tires and make sure the 4WD light is honest.",
      "145,000 miles. Service records matter.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you go.",
      "Ask for the out-the-door price. Fees can push these past $8,000.",
      "Get a pre-purchase inspection. A dealer lot is not a mechanical guarantee.",
    ],
  },
  {
    id: "camry-2010-sugar-land",
    year: 2010,
    make: "Toyota",
    model: "Camry",
    trim: "LE",
    price: 6399,
    priceNote: "No CarGurus estimate",
    miles: 168889,
    city: "Sugar Land, TX",
    drive: "about 28 min from Seven Lakes",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Compass Autos LLC",
    color: "Silver",
    drivetrain: "169 hp 2.5L I4, 6-Speed Automatic Overdrive",
    mpg: "",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/28/01/09/2010_toyota_camry-pic-1261447374969818234-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/459698900",
    vin: "4T4BF3EK3AR016238",
    sellerSays: "Compass Autos LLC in Sugar Land, TX. 2010 Toyota Camry LE. Silver. 169 hp 2.5L I4. 6-Speed Automatic Overdrive. 168,889 miles. 7 days on CarGurus. Asking $6,399.",
    why: "CarGurus rates this unscored. CarGurus did not publish an estimate. Sugar Land, about 28 minutes from Seven Lakes. 168,000 miles is why it is $6,399. CarGurus did not score a deal.",
    watch: [
      "6-speed automatic. These like their fluid changed.",
      "No deal score, so do not treat the price as a verified bargain. The engine year is still the right one.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you go.",
      "Ask for the out-the-door price. Fees can push these past $8,000.",
      "Get a pre-purchase inspection. A dealer lot is not a mechanical guarantee.",
    ],
  },
  {
    id: "fit-2013-houston",
    year: 2013,
    make: "Honda",
    model: "Fit",
    trim: "Base",
    price: 7699,
    priceNote: "CarGurus estimate $8,591",
    miles: 108901,
    city: "Houston, TX",
    drive: "in Houston",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Texas Perfect Auto",
    color: "White",
    drivetrain: "117 hp 1.5L I4, Transmission was not named on the listing",
    mpg: "",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/08/07/05/45/2013_honda_fit-pic-6110712211789462106-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/455561068",
    vin: "JHMGE8H3XDC080469",
    sellerSays: "Texas Perfect Auto in Houston, TX. 2013 Honda Fit Base. White. 117 hp 1.5L I4. Transmission was not named on the listing. 108,901 miles. 54 days on CarGurus. Asking $7,699.",
    why: "CarGurus rates this a good price. CarGurus estimate $8,591, about $892 under that. Lowest miles in this local set, 108,000, in Houston. Good price versus an estimate near $8,600.",
    watch: [
      "The listing did not name the transmission. A 2013 Fit automatic is a regular 5-speed, not a CVT. Confirm it.",
      "Plugs and coils are due around this mileage.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you go.",
      "Ask for the out-the-door price. Fees can push these past $8,000.",
      "Get a pre-purchase inspection. A dealer lot is not a mechanical guarantee.",
    ],
  },
  {
    id: "corolla-2013-houston",
    year: 2013,
    make: "Toyota",
    model: "Corolla",
    trim: "LE",
    price: 7995,
    priceNote: "CarGurus estimate $9,055",
    miles: 124401,
    city: "Houston, TX",
    drive: "in Houston",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Drive 4 Less Auto Sales",
    color: "Gray",
    drivetrain: "132 hp 1.8L I4, 4-Speed Automatic",
    mpg: "",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/25/04/22/2013_toyota_corolla-pic-625812036988172734-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/459881565",
    vin: "5YFBU4EE1DP083068",
    sellerSays: "Drive 4 Less Auto Sales in Houston, TX. 2013 Toyota Corolla LE. Gray. 132 hp 1.8L I4. 4-Speed Automatic. 124,401 miles. 5 days on CarGurus. Asking $7,995.",
    why: "CarGurus rates this a good price. CarGurus estimate $9,055, about $1,060 under that. 2013 Corolla in Houston, 124,000 miles, good price, 1.8 and a 4-speed automatic.",
    watch: [
      "It is $7,995 before fees. Get the out-the-door price.",
      "Houston is allowed. It is not a 30-minute drive from campus or from Seven Lakes.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you go.",
      "Ask for the out-the-door price. Fees can push these past $8,000.",
      "Get a pre-purchase inspection. A dealer lot is not a mechanical guarantee.",
    ],
  },
  {
    id: "civic-2009-houston",
    year: 2009,
    make: "Honda",
    model: "Civic",
    trim: "LX",
    price: 6499,
    priceNote: "CarGurus estimate $7,100",
    miles: 129825,
    city: "Houston, TX",
    drive: "in Houston",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Auto Ride",
    color: "Red",
    drivetrain: "140 hp 1.8L I4, 5-Speed Automatic Overdrive",
    mpg: "",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/08/01/03/22/2009_honda_civic-pic-646474522501304399-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/454962973",
    vin: "2HGFA16529H534675",
    sellerSays: "Auto Ride in Houston, TX. 2009 Honda Civic LX. Red. 140 hp 1.8L I4. 5-Speed Automatic Overdrive. 129,825 miles. 60 days on CarGurus. Asking $6,499.",
    why: "CarGurus rates this a good price. CarGurus estimate $7,100, about $601 under that. Houston, regular automatic, good price.",
    watch: [
      "2006 to 2011 Civic paint can peel. Look at the roof in the sun.",
      "In drive, brake held, the engine should not rock. Mounts crack on this generation.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you go.",
      "Ask for the out-the-door price. Fees can push these past $8,000.",
      "Get a pre-purchase inspection. A dealer lot is not a mechanical guarantee.",
    ],
  },
  {
    id: "accord-2008-houston",
    year: 2008,
    make: "Honda",
    model: "Accord",
    trim: "EX-L",
    price: 6600,
    priceNote: "CarGurus estimate $7,181",
    miles: 130754,
    city: "Houston, TX",
    drive: "in Houston",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Enterprise Motors Car Inc",
    color: "BLACK",
    drivetrain: "177 hp 2.4L I4, Automatic",
    mpg: "",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/05/11/52/2008_honda_accord-pic-4380754853118914270-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/458219482",
    vin: "1HGCP26868A069915",
    sellerSays: "Enterprise Motors Car Inc in Houston, TX. 2008 Honda Accord EX-L. BLACK. 177 hp 2.4L I4. Automatic. 130,754 miles. 25 days on CarGurus. Asking $6,600.",
    why: "CarGurus rates this a good price. CarGurus estimate $7,181, about $581 under that. 2008 Accord EX-L in Houston, 2.4 four-cylinder, not the V6. Good price.",
    watch: [
      "Cold-start tick is common and usually the VTC actuator.",
      "Some of these engines use oil. Read the dipstick.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you go.",
      "Ask for the out-the-door price. Fees can push these past $8,000.",
      "Get a pre-purchase inspection. A dealer lot is not a mechanical guarantee.",
    ],
  },
  {
    id: "corolla-2011-houston",
    year: 2011,
    make: "Toyota",
    model: "Corolla",
    trim: "LE",
    price: 6995,
    priceNote: "CarGurus estimate $7,370",
    miles: 138056,
    city: "Houston, TX",
    drive: "in Houston",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Drive 4 Less Auto Sales",
    color: "Gray",
    drivetrain: "132 hp 1.8L I4, 4-Speed Automatic",
    mpg: "",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/20/04/09/2011_toyota_corolla-pic-3177924937826987367-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/459454576",
    vin: "2T1BU4EE5BC673702",
    sellerSays: "Drive 4 Less Auto Sales in Houston, TX. 2011 Toyota Corolla LE. Gray. 132 hp 1.8L I4. 4-Speed Automatic. 138,056 miles. 10 days on CarGurus. Asking $6,995.",
    why: "CarGurus rates this a good price. CarGurus estimate $7,370, about $375 under that. 2011 Corolla in Houston, good price, 4-speed automatic.",
    watch: [
      "138,000 miles. Ask for oil-change records.",
      "Same store as the 2013 Corolla if you want to see both.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you go.",
      "Ask for the out-the-door price. Fees can push these past $8,000.",
      "Get a pre-purchase inspection. A dealer lot is not a mechanical guarantee.",
    ],
  },
  {
    id: "civic-2008-houston",
    year: 2008,
    make: "Honda",
    model: "Civic",
    trim: "EX-L",
    price: 5599,
    priceNote: "CarGurus estimate $5,826",
    miles: 143381,
    city: "Houston, TX",
    drive: "in Houston",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Direct Car Company",
    color: "WHITE",
    drivetrain: "140 hp 1.8L I4, Automatic",
    mpg: "",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/16/16/51/2008_honda_civic-pic-8417807202013014716-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/458273630",
    vin: "2HGFA16978H534091",
    sellerSays: "Direct Car Company in Houston, TX. 2008 Honda Civic EX-L. WHITE. 140 hp 1.8L I4. Automatic. 143,381 miles. 24 days on CarGurus. Asking $5,599.",
    why: "CarGurus rates this a good price. CarGurus estimate $5,826, about $227 under that. Houston, and the ask is under the CarGurus estimate. Good price at $5,599.",
    watch: [
      "EX-L means more equipment to test, and this generation peels paint.",
      "143,000 miles is fine if the mounts and the A/C are honest.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you go.",
      "Ask for the out-the-door price. Fees can push these past $8,000.",
      "Get a pre-purchase inspection. A dealer lot is not a mechanical guarantee.",
    ],
  },
  {
    id: "crv-2011-houston",
    year: 2011,
    make: "Honda",
    model: "CR-V",
    trim: "EX FWD",
    price: 7990,
    priceNote: "CarGurus estimate $8,491",
    miles: 147000,
    city: "Houston, TX",
    drive: "in Houston",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Executive Motor Group LLC.",
    color: "BLUE",
    drivetrain: "180 hp 2.4L I4, Automatic",
    mpg: "",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/16/10/54/2011_honda_cr-v-pic-8812423676519461840-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/459001296",
    vin: "5J6RE3H58BL006750",
    sellerSays: "Executive Motor Group LLC. in Houston, TX. 2011 Honda CR-V EX FWD. BLUE. 180 hp 2.4L I4. Automatic. 147,000 miles. 14 days on CarGurus. Asking $7,990.",
    why: "CarGurus rates this a good price. CarGurus estimate $8,491, about $501 under that. 2011 CR-V EX in Houston, good price.",
    watch: [
      "Run the A/C on max. The compressor on 2007 to 2011 CR-Vs is the expensive failure.",
      "EX: check the sunroof drains.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you go.",
      "Ask for the out-the-door price. Fees can push these past $8,000.",
      "Get a pre-purchase inspection. A dealer lot is not a mechanical guarantee.",
    ],
  },
  {
    id: "camry-2009-houston",
    year: 2009,
    make: "Toyota",
    model: "Camry",
    trim: "LE",
    price: 6500,
    priceNote: "CarGurus estimate $6,304",
    miles: 150388,
    city: "Houston, TX",
    drive: "in Houston",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Group 1 Toyota Southwest Houston",
    color: "Aloe Green Metallic",
    drivetrain: "158 hp 2.4L I4, Automatic",
    mpg: "",
    verdict: "Check first",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/10/23/44/2009_toyota_camry-pic-1183514645014337897-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/456358162",
    vin: "4T1BE46K99U835591",
    sellerSays: "Group 1 Toyota Southwest Houston in Houston, TX. 2009 Toyota Camry LE. Aloe Green Metallic. 158 hp 2.4L I4. Automatic. 150,388 miles. 44 days on CarGurus. Asking $6,500.",
    why: "CarGurus rates this a fair price. CarGurus estimate $6,304, about $196 over that. Group 1 Toyota in Houston, so the store is real. The engine year is still the risky one.",
    watch: [
      "Dipstick cold, then after a drive. Ask how often they add oil.",
      "The ask is a little over the CarGurus estimate. You are not getting a bargain on a bad year.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you go.",
      "Ask for the out-the-door price. Fees can push these past $8,000.",
      "Get a pre-purchase inspection. A dealer lot is not a mechanical guarantee.",
    ],
  },
  {
    id: "corolla-2013-houston-direct",
    year: 2013,
    make: "Toyota",
    model: "Corolla",
    trim: "LE",
    price: 6499,
    priceNote: "CarGurus estimate $7,929",
    miles: 167304,
    city: "Houston, TX",
    drive: "in Houston",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Direct Car Company",
    color: "BLACK",
    drivetrain: "132 hp 1.8L I4, Automatic",
    mpg: "",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/25/03/54/2013_toyota_corolla-pic-5040574950869243272-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/459289270",
    vin: "5YFBU4EE4DP078169",
    sellerSays: "Direct Car Company in Houston, TX. 2013 Toyota Corolla LE. BLACK. 132 hp 1.8L I4. Automatic. 167,304 miles. 12 days on CarGurus. Asking $6,499.",
    why: "CarGurus rates this a great price. CarGurus estimate $7,929, about $1,430 under that. Another 2013 Corolla in Houston, higher miles, and CarGurus calls the price great.",
    watch: [
      "167,000 miles. The great-price rating is about the odometer, not a secret low-mile car.",
      "Automatic. It should shift cleanly.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you go.",
      "Ask for the out-the-door price. Fees can push these past $8,000.",
      "Get a pre-purchase inspection. A dealer lot is not a mechanical guarantee.",
    ],
  },
  {
    id: "fit-2012-houston",
    year: 2012,
    make: "Honda",
    model: "Fit",
    trim: "Sport",
    price: 6950,
    priceNote: "CarGurus estimate $6,425",
    miles: 164920,
    city: "Houston, TX",
    drive: "in Houston",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "Autohaus Expo LLC",
    color: "Red",
    drivetrain: "117 hp 1.5L I4, 5-Speed Automatic",
    mpg: "",
    verdict: "Strong",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/23/20/38/2012_honda_fit-pic-1755029092829036941-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/459104608",
    vin: "JHMGE8H52CC013557",
    sellerSays: "Autohaus Expo LLC in Houston, TX. 2012 Honda Fit Sport. Red. 117 hp 1.5L I4. 5-Speed Automatic. 164,920 miles. 14 days on CarGurus. Asking $6,950.",
    why: "CarGurus rates this a fair price. CarGurus estimate $6,425, about $525 over that. Houston Fit with a 5-speed automatic. The price is only a fair rating, under their estimate by a little.",
    watch: [
      "164,000 miles. Coils and plugs.",
      "Fair rating means do not talk yourself into a deal that is not there.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you go.",
      "Ask for the out-the-door price. Fees can push these past $8,000.",
      "Get a pre-purchase inspection. A dealer lot is not a mechanical guarantee.",
    ],
  },
  {
    id: "accord-2015-sugar-land",
    year: 2015,
    make: "Honda",
    model: "Accord",
    trim: "LX",
    price: 7400,
    priceNote: "CarGurus estimate $9,030",
    miles: 175700,
    city: "Sugar Land, TX",
    drive: "about 28 min from Seven Lakes",
    owners: "Not stated on the dealer listing",
    title: "Not in the CarGurus summary. Read the history report.",
    seller: "Dealer",
    dealer: "HK AUTOS",
    color: "Obsidian Blue Pearl",
    drivetrain: "185 hp 2.4L I4, Continuously Variable Transmission",
    mpg: "",
    verdict: "Check first",
    photos: [
      "https://static.cargurus.com/images/forsale/2026/09/25/04/22/2015_honda_accord-pic-1640636138404875848-1024x768.jpeg",
    ],
    listingUrl: "https://www.cargurus.com/details/459881793",
    vin: "1HGCR2F31FA056131",
    sellerSays: "HK AUTOS in Sugar Land, TX. 2015 Honda Accord LX. Obsidian Blue Pearl. 185 hp 2.4L I4. Continuously Variable Transmission. 175,700 miles. 5 days on CarGurus. Asking $7,400.",
    why: "CarGurus rates this a great price. CarGurus estimate $9,030, about $1,630 under that. Sugar Land, about 28 minutes from Seven Lakes. Great price on paper, CVT in the car.",
    watch: [
      "Shudder off the line is a no.",
      "175,000 miles on a CVT needs a fluid-change receipt.",
    ],
    check: [
      "Open the CarGurus listing and run a history report on the VIN before you go.",
      "Ask for the out-the-door price. Fees can push these past $8,000.",
      "Get a pre-purchase inspection. A dealer lot is not a mechanical guarantee.",
    ],
  },
];
